const QUESTIONS = [
  // Normal/Casual (100+)
  "What is your favorite food?",
  "What is something you are really good at?",
  "What is your dream vacation destination?",
  "What did you want to be when you grew up?",
  "What is your hidden talent?",
  "How many cups of coffee or tea do you drink per day?",
  "What is your most-used emoji?",
  "What is your go-to karaoke song?",
  "What is the weirdest food you actually enjoy?",
  "What is your favorite movie or TV show?",
  "What's a skill you'd love to learn?",
  "What's your go-to comfort activity?",
  "What's the best advice you've ever received?",
  "What's your guilty pleasure?",
  "What's a hobby you've picked up recently?",
  "What's your favorite way to spend a lazy Sunday?",
  "What's the most interesting thing in your room right now?",
  "What's your favorite type of cuisine?",
  "What's a bucket list item you're determined to cross off?",
  "What's your spirit animal and why?",
  "If you could have any superpower, what would it be?",
  "What's your most controversial opinion?",
  "What's the best compliment you've ever received?",
  "What's your favorite way to get exercise?",
  "What's a song you can't stop listening to?",
  "If you could travel anywhere right now, where would it be?",
  "What's your favorite type of weather?",
  "What's the most daring thing you've ever done?",
  "What's your go-to snack?",
  "What's a skill you're surprisingly good at?",
  "If you could have dinner with anyone, who would it be?",
  "What's your biggest pet peeve?",
  "What's your favorite book or author?",
  "What's the best vacation you've ever taken?",
  "What's your lucky number or color?",
  "What's a gift you'd love to receive?",
  "What's your favorite childhood memory?",
  "What's the most interesting job you've ever had?",
  "What's your go-to mode of transportation?",
  "What's a goal you're working toward?",
  "If you could live in any era, which would it be?",
  "What's your favorite season and why?",
  "What's the coolest thing someone has ever done for you?",
  "What's your favorite type of music?",
  "If you could master any skill instantly, what would it be?",
  "What's your proudest achievement?",
  "What's your favorite way to relax?",
  "What's the best deal you've ever found?",
  "What's your favorite word?",
  "What's your morning routine like?",
  "If you could change one thing about yourself, what would it be?",
  "What's your favorite breakfast food?",
  "What's the funniest thing that's ever happened to you?",
  "What's your ideal weekend look like?",
  "What's a class or workshop you'd love to take?",
  "What's your favorite type of dessert?",
  "What's the best advice you'd give to your younger self?",
  "What's your favorite board game or video game?",
  "What's something you're secretly proud of?",
  "What's your favorite city you've visited?",
  "What's your favorite restaurant?",
  "What's something that makes you laugh every time?",
  "What's your favorite holiday?",
  "What's the scariest movie you've ever watched?",
  "What's your favorite indoor activity?",
  "What's the best compliment you could give someone?",
  "What's your favorite outdoor activity?",
  "What's a talent you wish you had?",
  "What's your favorite type of weather for outdoor activities?",
  "What's the best meal you've ever had?",
  "What's your favorite place to hang out?",
  "What's something that always cheers you up?",
  "What's your favorite type of plant or flower?",
  "What's the most useful thing you own?",
  "What's a promise you've kept to yourself?",
  "What's your favorite type of cuisine to cook?",
  "What's something you've learned recently that surprised you?",
  "What's your favorite app on your phone?",
  "What's the best gift you've ever given?",
  "What's your favorite way to spend time with friends?",
  "What's something you collect?",
  "What's your favorite type of animal?",
  "What's the best thing about where you live?",
  "What's your favorite type of candy or snack?",
  "What's something you're grateful for?",
  "What's your favorite memory with your family?",
  "What's a mistake that taught you something valuable?",
  "What's your favorite type of exercise?",
  "What's the most beautiful place you've been?",
  "What's your favorite bedtime ritual?",
  "What's something you do that relaxes you?",
  "What's your favorite type of music to listen to?",
  "What's the best thing about your job?",
  "What's your favorite time of day?",

  // Weird/Quirky (150+)
  "If your life was a TV show, what would it be called?",
  "What's the weirdest habit you have?",
  "If you were a vegetable, which one would you be?",
  "What's the strangest dream you've ever had?",
  "If you could only eat one food forever, what would it be?",
  "What's something you do that you think is weird but normal to you?",
  "If you had to describe yourself as a pasta shape, which would you be?",
  "What's the weirdest thing you've Googled?",
  "If you could be any inanimate object, what would you be?",
  "What's the most unusual thing you're afraid of?",
  "If your pet could talk, what would it say about you?",
  "What's the weirdest compliment you've ever received?",
  "If you were a kitchen appliance, which would you be?",
  "What's the most useless skill you have?",
  "If you could only wear one color forever, what would it be?",
  "What's the weirdest food combination you actually enjoy?",
  "If you were a pizza topping, which would you be?",
  "What's the most embarrassing thing in your search history?",
  "If you had to give up one of your five senses, which would it be?",
  "What's the weirdest reason you've cried?",
  "If you could only speak in movie quotes, what movies would you need?",
  "What's the silliest fear you have?",
  "If you were a superhero, what would your weakness be?",
  "What's the weirdest place you've fallen asleep?",
  "If you could teleport anywhere right now, where would it be?",
  "What's the most awkward conversation you've ever had?",
  "If you were a mythical creature, what would you be?",
  "What's the weirdest nickname you've ever had?",
  "If your life had a soundtrack, what song would play right now?",
  "What's the most bizarre thing you've bought online?",
  "If you could only use one arm for a day, how would you survive?",
  "What's the weirdest trend you've participated in?",
  "If you were a type of weather, what would you be?",
  "What's the most random talent you have?",
  "If you could swap lives with someone for a day, who would it be?",
  "What's the weirdest compliment about your appearance?",
  "If you were a dessert, which would you be?",
  "What's the most ridiculous argument you've ever had?",
  "If you could talk to animals, which would you ask questions?",
  "What's the weirdest thing you've done while drunk or very tired?",
  "If you were a car, what type would you be?",
  "What's the most random thing in your bag right now?",
  "If you could invent a new holiday, what would it celebrate?",
  "What's the weirdest smell you actually like?",
  "If you were a monster, what would your special power be?",
  "What's the most ridiculous thing you've ever Googled at 3am?",
  "If you could have any animal as a pet, what would it be?",
  "What's the weirdest recurring dream you have?",
  "If you were a type of cheese, which would you be?",
  "What's the most random knowledge you have?",
  "If you could curse someone with a minor inconvenience, what would it be?",
  "What's the weirdest thing you've found in your pocket?",
  "If you were a piece of furniture, what would you be?",
  "What's the most embarrassing song you love?",
  "If you had to choose between flying or invisibility, which would you choose?",
  "What's the weirdest thing you've said to your pet?",
  "If you were a cocktail, what would be your ingredients?",
  "What's the most random fact you know?",
  "If you could only watch one type of movie for life, which would it be?",
  "What's the weirdest texture you can think of?",
  "If you were a planet, which would you be?",
  "What's the most ridiculous reason you've been late to something?",
  "If you could have any accent, which would you choose?",
  "What's the weirdest thing you've done for attention?",
  "If you were a mathematical equation, what would you be?",
  "What's the most random compliment you've given someone?",
  "If you could eliminate one type of insect, which would it be?",
  "What's the weirdest thing you've overheard?",
  "If you were a type of dance, which would you be?",
  "What's the most embarrassing autocorrect fail you've had?",
  "If you could have dinner with any fictional character, who would it be?",
  "What's the weirdest thing you've pretended to understand?",
  "If you were a type of cloud, which would you be?",
  "What's the most random reason you've laughed?",
  "If you had to give yourself a new name, what would it be?",
  "What's the weirdest thing you've gotten in trouble for?",
  "If you were a direction, which would you be?",
  "What's the most useless superpower you could have?",
  "If you could change your name to a place, which place would you choose?",
  "What's the weirdest thing you've confessed to someone?",
  "If you were a type of tree, which would you be?",
  "What's the most random thing that made you angry?",
  "If you could see in any color other than normal, what would you choose?",
  "What's the weirdest rule you have for yourself?",
  "If you were a type of book, which would you be?",
  "What's the most embarrassing thing you've done in public?",
  "If you could only eat foods of one color, which color would you choose?",
  "What's the weirdest thing about your family?",
  "If you were a musical instrument, which would you be?",
  "What's the most random thing you've cried about?",
  "If you could live in any fictional world, which would it be?",
  "What's the weirdest lie you've ever told?",
  "If you were a type of bread, which would you be?",
  "What's the most ridiculous thing you believe?",
  "If you could have any job, what would it be?",
  "What's the weirdest thing you've felt embarrassed about?",
  "If you were a historical figure, who would you be?",
  "What's the most random thing you've learned on the internet?",
  "If you could only wear clothes from one decade, which would you choose?",
  "What's the weirdest thing someone has asked you?",
  "If you were a type of flower, which would you be?",
  "What's the most embarrassing thing your parents have told others?",
  "If you could have any skill without practicing, what would it be?",
  "What's the weirdest thing you've done when nobody was watching?",

  // Deep/Personal (100+)
  "What's something you want to accomplish before you die?",
  "What's a fear you've overcome?",
  "What's something you believe in strongly?",
  "What's the biggest risk you've ever taken?",
  "What's a lesson life has taught you?",
  "What's something you're working on improving about yourself?",
  "What's the most important thing in your life?",
  "What's something you regret?",
  "What's a dream you've let go of?",
  "What's something you've forgiven someone for?",
  "What's the most meaningful moment of your life?",
  "What's something you're passionate about?",
  "What's a value that's important to you?",
  "What's something you'd change about the world?",
  "What's the hardest thing you've ever done?",
  "What's something that inspires you?",
  "What's a mistake that made you grow?",
  "What's something you're afraid to admit?",
  "What's the most important relationship in your life?",
  "What's a goal you're too scared to say out loud?",
  "What's something you wish you'd done differently?",
  "What's a moment that changed your perspective?",
  "What's something you're learning about yourself lately?",
  "What's the best piece of advice someone gave you?",
  "What's something you're grateful for that you take for granted?",
  "What's a way you'd like to grow as a person?",
  "What's something you've learned from your mistakes?",
  "What's the most important lesson your family taught you?",
  "What's something you want people to know about you?",
  "What's a challenge you're currently facing?",
  "What's something you're proud of accomplishing?",
  "What's a hope you have for the future?",
  "What's something you've had to let go of?",
  "What's the most difficult truth you've accepted?",
  "What's something you wish you were braver about?",
  "What's a way you want to be remembered?",
  "What's something you're learning to accept about yourself?",
  "What's the best thing someone's done for you?",
  "What's a way you've helped someone recently?",
  "What's something you're still figuring out?",
  "What's a relationship that's shaped who you are?",
  "What's something you do that makes you feel alive?",
  "What's a moment you felt truly loved?",
  "What's something you're finally at peace with?",
  "What's a quality you admire in others?",
  "What's something you're still working through?",
  "What's the most important thing you've learned about people?",
  "What's a way you've changed for the better?",
  "What's something you're learning to be patient with?",
  "What's a dream that's become reality?",
  "What's something you need to hear right now?",
  "What's the biggest lesson you've learned from friendship?",
  "What's something you wish you'd told someone?",
  "What's a way you've supported someone else?",
  "What's the most meaningful conversation you've had?",
  "What's something you're learning to prioritize?",
  "What's a fear that's getting smaller?",
  "What's something you'd tell your younger self?",
  "What's a moment of clarity you've had?",
  "What's something you're glad happened?",
  "What's the most important thing in a friendship?",
  "What's something you're learning about yourself?",
  "What's a way you want to improve your life?",
  "What's something that's helped you through hard times?",
  "What's the most valuable lesson you've learned?",
  "What's something you want to be known for?",
  "What's a moment that made you feel grateful?",
  "What's something you're learning to accept?",
  "What's the best thing about being you?",
  "What's something you're still discovering about yourself?",
  "What's a way you've grown since last year?",
  "What's something that brings you peace?",
  "What's the most important thing you can do for someone?",
  "What's something you're proud of about your life?",
  "What's a moment that shaped your values?",
  "What's something you're learning to be grateful for?",
  "What's the best version of yourself you've been?",
  "What's something you wish you'd learned earlier?",
  "What's a way you want to impact others?",
  "What's the most important thing you've realized?",
  "What's something you're finally understanding?",
  "What's a moment you felt truly free?",
  "What's something you want to master?",
  "What's the most important relationship you have?",
  "What's something you're learning to love about yourself?",
  "What's a way you've become stronger?",
  "What's something that's worth the struggle?",

  // Random Fun (100+)
  "What would you name your boat if you had one?",
  "What's your go-to dance move?",
  "If you were a crayon, what color would you be?",
  "What's your favorite useless fact?",
  "If you had a warning label, what would it say?",
  "What's your favorite word that's fun to say?",
  "If you were a sandwich, what would be in you?",
  "What's the most random thing in your notes app?",
  "If your life was a movie, what would the tagline be?",
  "What's your favorite way to procrastinate?",
  "If you could have any accent when you speak, which would you choose?",
  "What's the silliest thing you've googled?",
  "If you were a type of cookie, which would you be?",
  "What's your favorite inside joke?",
  "If you could only use three emojis forever, which would you choose?",
  "What's the most random compliment you've received?",
  "If you were a type of beverage, which would you be?",
  "What's your favorite thing to do when you're bored?",
  "If you had a podcast, what would it be about?",
  "What's the weirdest food you've eaten willingly?",
  "If you were a type of hat, which would you be?",
  "What's your favorite punctuation mark?",
  "If you could name a species after yourself, what would it be?",
  "What's the most ridiculous achievement you're proud of?",
  "If you were a type of fruit, which would you be?",
  "What's your favorite thing to do that wastes time?",
  "If you could only send memes as communication, how would you survive?",
  "What's the most random place you've taken a photo?",
  "If you were a type of nut, which would you be?",
  "What's your favorite way to annoy someone affectionately?",
  "If you could only eat dessert, what would you choose?",
  "What's the most random person you follow on social media?",
  "If you were a type of salad, which would you be?",
  "What's your favorite guilty pleasure snack?",
  "If you had a superpower that was actually useless, what would it be?",
  "What's the most random thing you've collected?",
  "If you were a type of sauce, which would you be?",
  "What's your favorite way to be lazy?",
  "If you could time travel to any time period for a day, when would it be?",
  "What's the most random thing you've bought and never used?",
  "If you were a type of noodle, which would you be?",
  "What's your favorite type of background noise?",
  "If you could be fictional for a day, who would you be?",
  "What's the most random thing you've seen in public?",
  "If you were a type of sauce spice level, which would you be?",
  "What's your favorite thing to do that nobody knows you do?",
  "If you could only wear one brand forever, which would it be?",
  "What's the most random Amazon purchase you've made?",
  "If you were a type of carb, which would you be?",
  "What's your favorite way to waste money?",
  "If you could be invisible for a day, what would you do?",
  "What's the most random thing you've learned from a meme?",
  "If you were a type of sauce, which would you be?",
  "What's your favorite useless skill?",
  "If you could live like a famous person for a week, who would it be?",
  "What's the most random thing you've found online?",
  "If you were a type of potato, which would you be?",
  "What's your favorite way to procrastinate from procrastinating?",
  "If you could only communicate through GIFs, how would you do it?",
  "What's the most random thing that's made you laugh recently?",
  "If you were a type of dressing, which would you be?",
  "What's your favorite random fact about yourself?",
  "If you could time travel to learn one thing, what would it be?",
  "What's the most random thing in your history that you're glad got deleted?",
  "If you were a type of bean, which would you be?",
  "What's your favorite way to spend money?",
  "If you could only eat food from one cuisine forever, which would it be?",
  "What's the most random thing you've screamed about?",
  "If you were a type of spice, which would you be?",
  "What's your favorite thing about being alive?",
  "If you could only listen to music from one genre, which would it be?",
  "What's the most random thing you've done on impulse?",
  "If you were a type of meat, which would you be?",
  "What's your favorite random thing about your life?",
  "If you could change your appearance for a week, what would you do?",
  "What's the most random thing you've overheard that stuck with you?",
  "If you were a type of vegetable, which would you be?",
  "What's your favorite thing that costs nothing?",
  "If you could only wear one outfit forever, what would it be?",
  "What's the most random thing you've done that turned out great?",
  "If you were a type of grain, which would you be?",
  "What's your favorite random memory?",
  "If you could see any concert in history, whose would it be?"
];

module.exports = QUESTIONS;
